name: Infrastructure CI

on:
  pull_request:
    paths:
      - 'infrastructure/**'

jobs:
  infrastructure-validation:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Validate Infrastructure
        run: echo "Validating infrastructure configs"